require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessActivitsController do

  # This should return the minimal set of attributes required to create a valid
  # BusinessActivit. As you add validations to BusinessActivit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BusinessActivitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all business_activits as @business_activits" do
      business_activit = BusinessActivit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:business_activits).should eq([business_activit])
    end
  end

  describe "GET show" do
    it "assigns the requested business_activit as @business_activit" do
      business_activit = BusinessActivit.create! valid_attributes
      get :show, {:id => business_activit.to_param}, valid_session
      assigns(:business_activit).should eq(business_activit)
    end
  end

  describe "GET new" do
    it "assigns a new business_activit as @business_activit" do
      get :new, {}, valid_session
      assigns(:business_activit).should be_a_new(BusinessActivit)
    end
  end

  describe "GET edit" do
    it "assigns the requested business_activit as @business_activit" do
      business_activit = BusinessActivit.create! valid_attributes
      get :edit, {:id => business_activit.to_param}, valid_session
      assigns(:business_activit).should eq(business_activit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusinessActivit" do
        expect {
          post :create, {:business_activit => valid_attributes}, valid_session
        }.to change(BusinessActivit, :count).by(1)
      end

      it "assigns a newly created business_activit as @business_activit" do
        post :create, {:business_activit => valid_attributes}, valid_session
        assigns(:business_activit).should be_a(BusinessActivit)
        assigns(:business_activit).should be_persisted
      end

      it "redirects to the created business_activit" do
        post :create, {:business_activit => valid_attributes}, valid_session
        response.should redirect_to(BusinessActivit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved business_activit as @business_activit" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessActivit.any_instance.stub(:save).and_return(false)
        post :create, {:business_activit => {}}, valid_session
        assigns(:business_activit).should be_a_new(BusinessActivit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessActivit.any_instance.stub(:save).and_return(false)
        post :create, {:business_activit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested business_activit" do
        business_activit = BusinessActivit.create! valid_attributes
        # Assuming there are no other business_activits in the database, this
        # specifies that the BusinessActivit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusinessActivit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => business_activit.to_param, :business_activit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested business_activit as @business_activit" do
        business_activit = BusinessActivit.create! valid_attributes
        put :update, {:id => business_activit.to_param, :business_activit => valid_attributes}, valid_session
        assigns(:business_activit).should eq(business_activit)
      end

      it "redirects to the business_activit" do
        business_activit = BusinessActivit.create! valid_attributes
        put :update, {:id => business_activit.to_param, :business_activit => valid_attributes}, valid_session
        response.should redirect_to(business_activit)
      end
    end

    describe "with invalid params" do
      it "assigns the business_activit as @business_activit" do
        business_activit = BusinessActivit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessActivit.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_activit.to_param, :business_activit => {}}, valid_session
        assigns(:business_activit).should eq(business_activit)
      end

      it "re-renders the 'edit' template" do
        business_activit = BusinessActivit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessActivit.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_activit.to_param, :business_activit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested business_activit" do
      business_activit = BusinessActivit.create! valid_attributes
      expect {
        delete :destroy, {:id => business_activit.to_param}, valid_session
      }.to change(BusinessActivit, :count).by(-1)
    end

    it "redirects to the business_activits list" do
      business_activit = BusinessActivit.create! valid_attributes
      delete :destroy, {:id => business_activit.to_param}, valid_session
      response.should redirect_to(business_activits_url)
    end
  end

end
